# Generated by Django 4.2.1 on 2023-05-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito_productos',
            options={'verbose_name': 'Producto del Carrito', 'verbose_name_plural': 'Productos del Carrito'},
        ),
        migrations.AlterModelOptions(
            name='categoria_usuario',
            options={'verbose_name': 'Categoría de Usuario', 'verbose_name_plural': 'Categorías de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='custom_user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='listadeseos',
            options={'verbose_name': 'Lista de Deseos', 'verbose_name_plural': 'Listas de Deseos'},
        ),
    ]
