# Generated by Django 4.2.1 on 2023-05-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_direccion_datos_adicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
