# Generated by Django 4.2.1 on 2023-05-24 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_direccion_options_alter_peticiones_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del carrito'),
        ),
        migrations.AlterField(
            model_name='peticiones',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio solicitado'),
        ),
    ]
