# Generated by Django 4.2.1 on 2023-05-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_carrito_usuario_alter_peticiones_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='foto_perfil',
            field=models.ImageField(default=0, upload_to='usuarios', verbose_name='Avatar de usuario'),
            preserve_default=False,
        ),
    ]
