# Generated by Django 4.2.1 on 2023-05-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_custom_user_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios', verbose_name='Avatar de usuario'),
        ),
    ]
