# Generated by Django 4.2.1 on 2023-06-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_producto_imagen'),
        ('usuarios', '0008_alter_custom_user_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_productos',
            name='talla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.talla', verbose_name='Talla'),
            preserve_default=False,
        ),
    ]
