# Generated by Django 4.2.1 on 2023-05-16 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de modificacion')),
            ],
        ),
        migrations.AlterModelOptions(
            name='pedido_producto',
            options={'verbose_name': 'Productos en Pedidos', 'verbose_name_plural': 'Productos en Pedidos'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.estado_pedido'),
        ),
    ]
