# Generated by Django 4.2.1 on 2023-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['numero_pedido']},
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
