# Generated by Django 4.2.1 on 2023-05-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_estado_pedido_alter_pedido_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado_pedido',
            options={'verbose_name': 'Estado del Pedido', 'verbose_name_plural': 'Estados de Pedidos'},
        ),
    ]
