# Generated by Django 4.2.1 on 2023-05-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo_pedido',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Código del pedido'),
        ),
    ]
