# Generated by Django 4.2.1 on 2023-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_codigo_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_pedido',
            name='descripcion',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
