# Generated by Django 4.2.1 on 2023-05-24 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_talla_options_alter_ajuste_created_and_more'),
        ('usuarios', '0006_alter_carrito_usuario_alter_peticiones_precio'),
        ('pedidos', '0008_alter_estado_pedido_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_producto',
            name='talla',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='productos.talla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='usuarios.direccion'),
            preserve_default=False,
        ),
    ]
