# Generated by Django 4.2.1 on 2023-05-25 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_pedido_producto_talla_alter_pedido_direccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['usuario']},
        ),
        migrations.AlterModelOptions(
            name='pedido_producto',
            options={'verbose_name': 'Productos del pedido', 'verbose_name_plural': 'Productos del pedido'},
        ),
        migrations.AlterField(
            model_name='pedido_producto',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
