# Generated by Django 4.2.1 on 2023-05-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_oferta_alter_producto_precio_oferta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajuste',
            options={'verbose_name': 'Ajuste de la Prenda', 'verbose_name_plural': 'Ajuste de la Prenda'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colores'},
        ),
        migrations.AlterModelOptions(
            name='producto_talla',
            options={'verbose_name': 'Talla del Producto', 'verbose_name_plural': 'Talla del Producto'},
        ),
        migrations.AlterModelOptions(
            name='tipo_prenda',
            options={'verbose_name': 'Tipo de Prenda', 'verbose_name_plural': 'Tipos de Prenda'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_tipo_prenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.tipo_prenda'),
        ),
    ]
