# Generated by Django 4.2.1 on 2023-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_talla_options_alter_talla_talla_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto_talla',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventario'},
        ),
        migrations.AlterField(
            model_name='ajuste',
            name='descripcion',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('superior', 'Superior'), ('inferior', 'Inferior'), ('accesorios', 'Accesorios'), ('zapatillas', 'Zapatillas')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='codigo_hex',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='descripcion',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_ajuste',
            field=models.ManyToManyField(to='productos.ajuste', verbose_name='Ajuste de la prenda'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_color',
            field=models.ManyToManyField(to='productos.color', verbose_name='Color(es) del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_marca',
            field=models.ManyToManyField(to='productos.marca', verbose_name='Marca de la prenda'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_tipo_prenda',
            field=models.ManyToManyField(to='productos.tipo_prenda', verbose_name='Tipo de prenda'),
        ),
    ]
