# Generated by Django 4.2.1 on 2023-05-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_ajuste_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='producto_tipo_prenda',
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_tipo_prenda',
            field=models.ManyToManyField(to='productos.tipo_prenda'),
        ),
    ]
