# Generated by Django 4.2.1 on 2023-05-16 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_producto_tipo_prenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talla',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talla',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de modificacion'),
        ),
    ]
