# Generated by Django 4.2.1 on 2023-05-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_talla_options_alter_ajuste_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_talla',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.talla', verbose_name='Talla'),
        ),
    ]
