# Generated by Django 4.2.1 on 2023-05-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_talla_created_talla_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
