# Generated by Django 4.2.1 on 2023-05-28 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_talla_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Destacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto destacado',
                'verbose_name_plural': 'Producto destacado',
            },
        ),
    ]
